# Generated by Django 6.0.5 on 2026-05-14 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publicity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="公示ID", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="标题", max_length=100)),
                ("content", models.TextField(db_column="内容")),
                (
                    "publish_time",
                    models.DateTimeField(auto_now_add=True, db_column="发布时间"),
                ),
                (
                    "collection_start",
                    models.DateTimeField(
                        blank=True, db_column="材料收集开始时间", null=True
                    ),
                ),
                (
                    "collection_end",
                    models.DateTimeField(
                        blank=True, db_column="材料收集截止时间", null=True
                    ),
                ),
                (
                    "need_material",
                    models.CharField(
                        choices=[("是", "是"), ("否", "否")],
                        db_column="是否需要提交材料",
                        default="否",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("进行中", "进行中"), ("已结束", "已结束")],
                        db_column="状态",
                        default="进行中",
                        max_length=10,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        db_column="发布人ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="published_publicities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "公示",
                "verbose_name_plural": "公示",
                "db_table": "公示",
            },
        ),
        migrations.CreateModel(
            name="PublicitySubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="提交ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "material_content",
                    models.TextField(blank=True, db_column="材料内容", null=True),
                ),
                (
                    "attachment_path",
                    models.CharField(
                        blank=True, db_column="材料附件路径", max_length=255, null=True
                    ),
                ),
                (
                    "submit_time",
                    models.DateTimeField(auto_now_add=True, db_column="提交时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("待审核", "待审核"),
                            ("已通过", "已通过"),
                            ("已驳回", "已驳回"),
                        ],
                        db_column="审核状态",
                        default="待审核",
                        max_length=10,
                    ),
                ),
                (
                    "review_time",
                    models.DateTimeField(blank=True, db_column="审核时间", null=True),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, db_column="审核意见", null=True),
                ),
                (
                    "publicity",
                    models.ForeignKey(
                        db_column="公示ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="submissions",
                        to="publicity.publicity",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        db_column="审核人ID",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reviewed_publicity_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="用户ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="publicity_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "公示材料提交记录",
                "verbose_name_plural": "公示材料提交记录",
                "db_table": "公示材料提交记录",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("publicity", "user"), name="uk_publicity_user"
                    )
                ],
            },
        ),
    ]
