# Generated by Django 6.0.5 on 2026-05-14 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="活动ID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="活动名称", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, db_column="活动描述", null=True),
                ),
                ("activity_time", models.DateTimeField(db_column="活动时间")),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="活动地点", max_length=100, null=True
                    ),
                ),
                (
                    "publish_time",
                    models.DateTimeField(auto_now_add=True, db_column="发布时间"),
                ),
                (
                    "checkin_code",
                    models.CharField(
                        blank=True, db_column="签到码", max_length=50, null=True
                    ),
                ),
                (
                    "checkin_deadline",
                    models.DateTimeField(
                        blank=True, db_column="签到截止时间", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("报名中", "报名中"),
                            ("进行中", "进行中"),
                            ("已结束", "已结束"),
                        ],
                        db_column="状态",
                        default="报名中",
                        max_length=10,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        db_column="发布人ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="published_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "活动",
                "verbose_name_plural": "活动",
                "db_table": "活动",
            },
        ),
        migrations.CreateModel(
            name="ActivityCheckIn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="签到ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "checkin_time",
                    models.DateTimeField(blank=True, db_column="签到时间", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("已签到", "已签到"), ("未签到", "未签到")],
                        db_column="签到状态",
                        default="未签到",
                        max_length=10,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        db_column="活动ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="checkins",
                        to="activities.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="用户ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="activity_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "活动签到记录",
                "verbose_name_plural": "活动签到记录",
                "db_table": "活动签到记录",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activity", "user"), name="uk_activity_sign"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="报名ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "registration_time",
                    models.DateTimeField(auto_now_add=True, db_column="报名时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("已报名", "已报名"), ("已取消", "已取消")],
                        db_column="报名状态",
                        default="已报名",
                        max_length=10,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        db_column="活动ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="registrations",
                        to="activities.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="用户ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="activity_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "活动报名记录",
                "verbose_name_plural": "活动报名记录",
                "db_table": "活动报名记录",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activity", "user"), name="uk_activity_user"
                    )
                ],
            },
        ),
    ]
