# Generated by Django 6.0.5 on 2026-05-14 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="通知ID", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="标题", max_length=100)),
                ("content", models.TextField(db_column="内容")),
                (
                    "publish_time",
                    models.DateTimeField(auto_now_add=True, db_column="发布时间"),
                ),
                (
                    "deadline",
                    models.DateTimeField(blank=True, db_column="截止时间", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("未发布", "未发布"),
                            ("已发布", "已发布"),
                            ("已过期", "已过期"),
                        ],
                        db_column="状态",
                        default="已发布",
                        max_length=10,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        db_column="用户ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "db_table": "通知",
            },
        ),
        migrations.CreateModel(
            name="NotificationReadRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="记录ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "read_time",
                    models.DateTimeField(blank=True, db_column="已读时间", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("未读", "未读"), ("已读", "已读")],
                        db_column="状态",
                        default="未读",
                        max_length=10,
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        db_column="通知ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="read_records",
                        to="notifications.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="用户ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="notification_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "通知已读记录",
                "verbose_name_plural": "通知已读记录",
                "db_table": "通知已读记录",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("notification", "user"), name="uk_notice_user"
                    )
                ],
            },
        ),
    ]
