# Generated by Django 6.0.5 on 2026-05-14 14:12

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        db_column="用户ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "student_id",
                    models.CharField(db_column="学号", max_length=20, unique=True),
                ),
                ("name", models.CharField(db_column="姓名", max_length=10)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("男", "男"), ("女", "女")],
                        db_column="性别",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True, db_column="班级", max_length=20, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_column="手机号",
                        max_length=11,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "political_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("群众", "群众"),
                            ("团员", "团员"),
                            ("预备党员", "预备党员"),
                            ("党员", "党员"),
                        ],
                        db_column="政治面貌",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(blank=True, db_column="入学时间", null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("普通学生", "普通学生"),
                            ("班长", "班长"),
                            ("团支书", "团支书"),
                        ],
                        db_column="角色",
                        default="普通学生",
                        max_length=10,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "用户",
            },
        ),
        migrations.CreateModel(
            name="MemberChangeRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="变更ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "change_content",
                    models.CharField(db_column="变更内容", max_length=100),
                ),
                (
                    "change_time",
                    models.DateTimeField(auto_now_add=True, db_column="变更时间"),
                ),
                (
                    "before_data",
                    models.CharField(
                        blank=True, db_column="变更前数据", max_length=255, null=True
                    ),
                ),
                (
                    "after_data",
                    models.CharField(
                        blank=True, db_column="变更后数据", max_length=255, null=True
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        db_column="操作人ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="operated_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="用户ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="member_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "成员变更记录",
                "verbose_name_plural": "成员变更记录",
                "db_table": "成员变更记录",
            },
        ),
        migrations.CreateModel(
            name="PartyArchive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="档案ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "political_identity",
                    models.CharField(
                        choices=[
                            ("群众", "群众"),
                            ("团员", "团员"),
                            ("预备党员", "预备党员"),
                            ("党员", "党员"),
                        ],
                        db_column="政治身份",
                        max_length=10,
                    ),
                ),
                (
                    "join_league_date",
                    models.DateField(blank=True, db_column="入团时间", null=True),
                ),
                (
                    "join_party_date",
                    models.DateField(blank=True, db_column="入党时间", null=True),
                ),
                (
                    "full_member_date",
                    models.DateField(blank=True, db_column="转正时间", null=True),
                ),
                (
                    "introducer_name",
                    models.CharField(
                        blank=True, db_column="介绍人姓名", max_length=50, null=True
                    ),
                ),
                (
                    "org_relation_status",
                    models.CharField(
                        choices=[("正常", "正常"), ("转出", "转出"), ("转入", "转入")],
                        db_column="组织关系状态",
                        default="正常",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="用户ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="party_archive",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "党团员档案",
                "verbose_name_plural": "党团员档案",
                "db_table": "党团员档案",
            },
        ),
    ]
