# Generated by Django 6.0.5 on 2026-05-14 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="任务ID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="任务名称", max_length=100)),
                (
                    "publish_time",
                    models.DateTimeField(auto_now_add=True, db_column="发布时间"),
                ),
                (
                    "registration_deadline",
                    models.DateTimeField(
                        blank=True, db_column="报名截止时间", null=True
                    ),
                ),
                (
                    "vote_start",
                    models.DateTimeField(
                        blank=True, db_column="投票开始时间", null=True
                    ),
                ),
                (
                    "vote_end",
                    models.DateTimeField(
                        blank=True, db_column="投票结束时间", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("报名中", "报名中"),
                            ("投票中", "投票中"),
                            ("已结束", "已结束"),
                        ],
                        db_column="状态",
                        default="报名中",
                        max_length=10,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        db_column="发布人ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="published_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "推优任务",
                "verbose_name_plural": "推优任务",
                "db_table": "推优任务",
            },
        ),
        migrations.CreateModel(
            name="RecommendationRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="报名ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "registration_time",
                    models.DateTimeField(auto_now_add=True, db_column="报名时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("待审核", "待审核"),
                            ("已通过", "已通过"),
                            ("已驳回", "已驳回"),
                        ],
                        db_column="审核状态",
                        default="待审核",
                        max_length=10,
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, db_column="审核意见", null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="用户ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="recommendation_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        db_column="任务ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="registrations",
                        to="recommendation.recommendationtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "推优报名",
                "verbose_name_plural": "推优报名",
                "db_table": "推优报名",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "user"), name="uk_task_user"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RecommendationVote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="投票ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "vote_time",
                    models.DateTimeField(auto_now_add=True, db_column="投票时间"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        db_column="被投票人ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="votes_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        db_column="任务ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="votes",
                        to="recommendation.recommendationtask",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        db_column="投票人ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="votes_cast",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "推优投票记录",
                "verbose_name_plural": "推优投票记录",
                "db_table": "推优投票记录",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "voter", "candidate"), name="uk_task_voter"
                    )
                ],
            },
        ),
    ]
