# Generated by Django 6.0.5 on 2026-05-14 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="记录ID", primary_key=True, serialize=False
                    ),
                ),
                ("attendance_date", models.DateField(db_column="考勤日期")),
                (
                    "status",
                    models.CharField(
                        choices=[("出勤", "出勤"), ("缺勤", "缺勤"), ("请假", "请假")],
                        db_column="考勤状态",
                        max_length=10,
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, db_column="备注", max_length=255, null=True
                    ),
                ),
                (
                    "recorder",
                    models.ForeignKey(
                        db_column="录入人ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="recorded_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="用户ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "考勤记录",
                "verbose_name_plural": "考勤记录",
                "db_table": "考勤记录",
            },
        ),
        migrations.CreateModel(
            name="AttendanceTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="考勤ID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="考勤名称", max_length=100)),
                ("attendance_time", models.DateTimeField(db_column="考勤时间")),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="考勤地点", max_length=100, null=True
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_column="用户ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_attendance_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "考勤任务",
                "verbose_name_plural": "考勤任务",
                "db_table": "考勤任务",
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="申请ID", primary_key=True, serialize=False
                    ),
                ),
                ("leave_date", models.DateField(db_column="请假日期")),
                ("reason", models.CharField(db_column="请假原因", max_length=255)),
                (
                    "apply_time",
                    models.DateTimeField(auto_now_add=True, db_column="申请时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("待审核", "待审核"),
                            ("已通过", "已通过"),
                            ("已驳回", "已驳回"),
                        ],
                        db_column="审核状态",
                        default="待审核",
                        max_length=10,
                    ),
                ),
                (
                    "review_comment",
                    models.CharField(
                        blank=True, db_column="审核意见", max_length=255, null=True
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        db_column="审核人ID",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reviewed_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="用户ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "请假申请",
                "verbose_name_plural": "请假申请",
                "db_table": "请假申请",
            },
        ),
    ]
