# Generated by Django 6.0.5 on 2026-05-14 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyMaterialUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="记录ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "material_name",
                    models.CharField(db_column="资料名称", max_length=100),
                ),
                (
                    "material_path",
                    models.CharField(db_column="资料路径", max_length=255),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, db_column="上传时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("待审核", "待审核"),
                            ("已通过", "已通过"),
                            ("已驳回", "已驳回"),
                        ],
                        db_column="审核状态",
                        default="待审核",
                        max_length=10,
                    ),
                ),
                (
                    "review_time",
                    models.DateTimeField(blank=True, db_column="审核时间", null=True),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, db_column="审核意见", null=True),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        db_column="审核人ID",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reviewed_party_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="用户ID",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="party_material_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "党团资料上传记录",
                "verbose_name_plural": "党团资料上传记录",
                "db_table": "党团资料上传记录",
            },
        ),
        migrations.CreateModel(
            name="ProofMaterial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="材料ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "material_name",
                    models.CharField(db_column="材料名称", max_length=100),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, db_column="上传时间"),
                ),
                (
                    "material_path",
                    models.CharField(db_column="材料路径", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("待审核", "待审核"),
                            ("通过", "通过"),
                            ("驳回", "驳回"),
                        ],
                        db_column="审核状态",
                        default="待审核",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="用户ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proof_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "证明材料",
                "verbose_name_plural": "证明材料",
                "db_table": "证明材料",
            },
        ),
    ]
